"""update article

Revision ID: 030d9b7a3bef
Revises: d725dc0ac082
Create Date: 2023-01-21 15:05:57.104809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '030d9b7a3bef'
down_revision = 'd725dc0ac082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author_model.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_model')
    # ### end Alembic commands ###
